name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3  # Use v3 instead of v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl https://clientele-statique.solutions.hydroquebec.com/config/indispo/indisponibilites.json| jq . > states.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

